variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_W: "10"
   ORD_SOUMET_C: "4"
   ORD_SOUMET_M: "8G"
   ORD_SOUMET_TMPFS: "1G"
stages:
   - build
   - test
   - package
   - deploy
   - trigger

before_script:
   - source ~/ci-admin/env/init.sh
   - export PIPELINE_SUBDIR=${ECCI_BUILD_DIR}/precaution/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}

#----- rhel-8-icelake-64_inteloneapi-2024.2.0

build:rhel-8-icelake-64_inteloneapi-2024.2.0:
   stage: build
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-icelake-64/inteloneapi-2024.2.0.sh
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2024.2.0
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2024.2.0
      - cmake ${SRC_DIR}
      - time make -j $NCPUS
   allow_failure: true

test:rhel-8-icelake-64_inteloneapi-2024.2.0:
   stage: test
   tags:
      - concurrent
   only:
     - master
     - alpha
     - /^dev.*$/
     - tags
   dependencies:
     - build:rhel-8-icelake-64_inteloneapi-2024.2.0
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-icelake-64/inteloneapi-2024.2.0.sh
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2024.2.0
      - make check
   allow_failure: true

package:rhel-8-icelake-64_inteloneapi-2024.2.0:
   stage: package
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
      - schedules
   dependencies:
      - build:rhel-8-icelake-64_inteloneapi-2024.2.0
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-icelake-64/inteloneapi-2024.2.0.sh
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2024.2.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}
   allow_failure: true

#----- rhel-8-icelake-64_inteloneapi-2022.1.2

build:rhel-8-icelake-64_inteloneapi-2022.1.2:
   stage: build
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-icelake-64/inteloneapi-2022.1.2.sh
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2022.1.2
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2022.1.2
      - cmake ${SRC_DIR}
      - time make -j $NCPUS

test:rhel-8-icelake-64_inteloneapi-2022.1.2:
   stage: test
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
   dependencies:
      - build:rhel-8-icelake-64_inteloneapi-2022.1.2
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-icelake-64/inteloneapi-2022.1.2.sh
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2022.1.2
      - make check

package:rhel-8-icelake-64_inteloneapi-2022.1.2:
   stage: package
   tags:
      - concurrent
   only:
      - master
      - alpha
      - tags
      - /^dev.*$/
      - schedules
   dependencies:
      - build:rhel-8-icelake-64_inteloneapi-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-icelake-64/inteloneapi-2022.1.2.sh
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- rhel-8-amd64_inteloneapi-2022.1.2

build:rhel-8-amd64_inteloneapi-2022.1.2:
   stage: build
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-amd-64/inteloneapi-2022.1.2.sh
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_rhel-8-amd64_inteloneapi-2022.1.2
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-amd64_inteloneapi-2022.1.2
      - cmake ${SRC_DIR}
      - time make -j $NCPUS

test:rhel-8-amd64_inteloneapi-2022.1.2:
   stage: test
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
   dependencies:
      - build:rhel-8-amd64_inteloneapi-2022.1.2
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-amd-64/inteloneapi-2022.1.2.sh
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-amd64_inteloneapi-2022.1.2
      - make check

package:rhel-8-amd64_inteloneapi-2022.1.2:
   stage: package
   tags:
      - concurrent
   only:
      - master
      - alpha
      - tags
      - /^dev.*$/
      - schedules
   dependencies:
      - build:rhel-8-amd64_inteloneapi-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-amd-64/inteloneapi-2022.1.2.sh
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-amd64_inteloneapi-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- rhel-8-amd64_gnu-9.3

build:rhel-8-amd64_gnu-9.3.0:
   stage: build
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-amd-64/gnu-9.3.0.sh 
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_rhel-8-amd64_gnu-9.3.0
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-amd64_gnu-9.3.0
      - cmake ${SRC_DIR}
      - time make -j $NCPUS

test:rhel-8-amd64_gnu-9.3.0:
   stage: test
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
   dependencies:
      - build:rhel-8-amd64_gnu-9.3.0
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-amd-64/gnu-9.3.0.sh 
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-amd64_gnu-9.3.0
      - make check

package:rhel-8-amd64_gnu-9.3.0:
   stage: package
   tags:
      - concurrent
   only:
      - master
      - alpha
      - tags
      - /^dev.*$/
      - schedules
   dependencies:
      - build:rhel-8-amd64_gnu-9.3.0
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-amd-64/gnu-9.3.0.sh 
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-amd64_gnu-9.3.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- rhel-8-icelake-64_inteloneapi-2021.4.0

build:rhel-8-icelake-64_inteloneapi-2021.4.0:
   stage: build
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-icelake-64/inteloneapi-2021.4.0.sh
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2021.4.0
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2021.4.0
      - cmake ${SRC_DIR}
      - time make -j $NCPUS

test:rhel-8-icelake-64_inteloneapi-2021.4.0:
   stage: test
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
   dependencies:
      - build:rhel-8-icelake-64_inteloneapi-2021.4.0
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-icelake-64/inteloneapi-2021.4.0.sh
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2021.4.0
      - make check

package:rhel-8-icelake-64_inteloneapi-2021.4.0:
   stage: package
   tags:
      - concurrent
   only:
      - master
      - alpha
      - tags
      - /^dev.*$/
      - schedules
   dependencies:
      - build:rhel-8-icelake-64_inteloneapi-2021.4.0
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-icelake-64/inteloneapi-2021.4.0.sh
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2021.4.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- ubuntu-22.04-amd64_inteloneapi-2022.1.2

build:ubuntu-22.04-amd64_inteloneapi-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: build
   tags:
      - concurrent
   only:
     - master
      - alpha
     - /^dev.*$/
     - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/inteloneapi-2022.1.2.sh
      - export ORDENV_PLAT=ubuntu-22.04-amd64-64
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2022.1.2
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2022.1.2
      - cmake ${SRC_DIR}
      - time make -j $NCPUS

test:ubuntu-22.04-amd64_inteloneapi-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: test
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
   dependencies:
      - build:ubuntu-22.04-amd64_inteloneapi-2022.1.2
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/inteloneapi-2022.1.2.sh
      - export ORDENV_PLAT=ubuntu-22.04-amd64-64
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2022.1.2
      - make check
      
package:ubuntu-22.04-amd64_inteloneapi-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: package
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
      - schedules
   dependencies:
      - build:ubuntu-22.04-amd64_inteloneapi-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/inteloneapi-2022.1.2.sh
      - export ORDENV_PLAT=ubuntu-22.04-amd64-64
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- ubuntu-22.04-amd64_inteloneapi-2023.2.0

build:ubuntu-22.04-amd64_inteloneapi-2023.2.0:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: build
   tags:
      - concurrent
   only:
     - master
      - alpha
     - /^dev.*$/
     - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/inteloneapi-2023.2.0.sh
      - export ORDENV_PLAT=ubuntu-22.04-amd64-64
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2023.2.0
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2023.2.0
      - cmake ${SRC_DIR}
      - time make -j $NCPUS

test:ubuntu-22.04-amd64_inteloneapi-2023.2.0:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: test
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
   dependencies:
      - build:ubuntu-22.04-amd64_inteloneapi-2023.2.0
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/inteloneapi-2023.2.0.sh
      - export ORDENV_PLAT=ubuntu-22.04-amd64-64
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2023.2.0
      - make check
      
package:ubuntu-22.04-amd64_inteloneapi-2023.2.0:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: package
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
      - schedules
   dependencies:
      - build:ubuntu-22.04-amd64_inteloneapi-2023.2.0
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/inteloneapi-2023.2.0.sh
      - export ORDENV_PLAT=ubuntu-22.04-amd64-64
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2023.2.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- ubuntu-22.04-amd64_gnu-11.4.0

build:ubuntu-22.04-amd64_gnu-11.4.0:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: build
   tags:
      - concurrent
   only:
     - master
      - alpha
     - /^dev.*$/
     - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/gnu.sh
      - export ORDENV_PLAT=ubuntu-22.04-amd64-64
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_gnu-11.4.0
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_gnu-11.4.0
      - cmake ${SRC_DIR}
      - time make -j $NCPUS

test:ubuntu-22.04-amd64_gnu-11.4.0:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: test
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
   dependencies:
      - build:ubuntu-22.04-amd64_gnu-11.4.0
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/gnu.sh
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs 
      - export ORDENV_PLAT=ubuntu-22.04-amd64-64
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_gnu-11.4.0
      - make check

package:ubuntu-22.04-amd64_gnu-11.4.0:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: package
   tags:
      - concurrent
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
      - schedules
   dependencies:
      - build:ubuntu-22.04-amd64_gnu-11.4.0
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/gnu.sh
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_gnu-11.4.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- rhel-8-amd64_gnu-14.1.0

build:rhel-8-amd64_gnu-14.1.0:
   stage: build
   tags:
      - concurrent
   only:
     - master
     - alpha
     - /^dev.*$/
     - tags
   script:
      - source ${ECCI_ENV}/latest/profile.sh
      - unset SSMUSE_LD_PREPEND
      - . r.load.dot /fs/ssm/main/opt/cmake/cmake-3.30.0
      - export MODULEPATH=~sidr000/modules:$MODULEPATH
      - module load gcc14
      - export EC_ARCH=Linux_x86-64/gnu-14.1.0
      - export COMP_ARCH=gnu-14.1.0
      - export ORDENV_PLAT=rhel-8-amd64-64
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - mkdir -pv ${PIPELINE_SUBDIR}/build_rhel-8-amd64_gnu-14.1.0
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-amd64_gnu-14.1.0
      - cmake ${SRC_DIR}
      - time make -j $NCPUS
   allow_failure: true

test:rhel-8-amd64_gnu-14.1.0:
   stage: test
   tags:
      - concurrent
   only:
     - master
     - alpha
     - /^dev.*$/
     - tags
   dependencies:
     - build:rhel-8-amd64_gnu-14.1.0
   script:
      - set +e
      - source ${ECCI_ENV}/latest/profile.sh
      - unset SSMUSE_LD_PREPEND
      - . r.load.dot /fs/ssm/main/opt/cmake/cmake-3.30.0
      - export MODULEPATH=~sidr000/modules:$MODULEPATH
      - module load gcc14
      - export EC_ARCH=Linux_x86-64/gnu-14.1.0
      - export COMP_ARCH=gnu-14.1.0
      - export ORDENV_PLAT=rhel-8-amd64-64
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-amd64_gnu-14.1.0
      - make check
   allow_failure: true
      
deploy:staging:
   stage: deploy
   only:
      - master
      - alpha
      - tags
      - /^dev.*$/
      - schedules
   script:
      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh utils ${CI_PROJECT_NAME} "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"

trigger:
   stage: trigger
   only:
      - master
      - alpha
      - /^dev.*$/
      - tags
      - schedules
   script:
      - curl -X POST -F token=${ECCI_TRIGGER_VGRID}     -F ref=${ECCI_VERSION_VGRID} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/114/trigger/pipeline
