variables:
    GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build

before_script:
  # Force color CMake output even when output is not TTY
  - export CLICOLOR_FORCE=true
  - export ORDENV_SITE_PROFILE=20210129
  - export ORDENV_COMM_PROFILE=eccc/20210309
  - export ORDENV_GROUP_PROFILE=eccc/cmc/1.9.4
  - set +e ; . /fs/ssm/main/env/ordenv-boot-20201118.sh ; set -e
  - source SETUP.sh

build_cmake:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-site
    - make
  artifacts:
    paths:
      - install-site
