variables:
    GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build

before_script:
  # Force color CMake output even when output is not TTY
  - export CLICOLOR_FORCE=true

build_intel:
  stage: build
  script:
    - source ~/ci-admin-bundle/environments/eccc-setup-intel.sh
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-site-intel
    - make
    - make check
    - make install
  artifacts:
    paths:
      - install-site

# build_gnu:
#   stage: build
#   script:
#     - source ~/ci-admin-bundle/environments/eccc-setup-gnu.sh
#     - mkdir build
#     - cd build
#     - cmake .. -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-site-gnu
#     - make
#     - make check
#     - make install
#   artifacts:
#     paths:
#       - install-site-gnu
