variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_W: "10"
   ORD_SOUMET_C: "4"
   ORD_SOUMET_M: "8G"
   ORD_SOUMET_TMPFS: "1G"

.env:
   build:
      - . r.load.dot ${ECCI_PROCESS_SSM}/libs

include:
   - project: 'RPN-SI/ci-admin'
     ref: dev
     file: '/ci/.gitlab-ci-config.yml'
      
deploy:staging:
   stage: deploy
   only:
      - master
      - alpha
      - tags
      - dev
      - dev_alpha
      - schedules
   script:
      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh utils ${CI_PROJECT_NAME} "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"

trigger:
   stage: trigger
   only:
      - master
      - alpha
      - dev
      - dev_alpha
      - tags
      - schedules
   script:
      - curl -X POST -F token=${ECCI_TRIGGER_VGRID}     -F ref=${ECCI_VERSION_VGRID} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/114/trigger/pipeline
