***S/R CRITSUP DEFIFIT LES CRITERES SUPLEMENTAIRES DE SELECTION
      SUBROUTINE CRITSUP(NI, NJ, NK, GRID, IG1, IG2, IG3, IG4)
      IMPLICIT NONE 
      INTEGER     NI, NJ, NK, GRID, IG1, IG2, IG3, IG4
*
*AUTEUR       AUTEUR YVON BOURASSA . JAN 90
*                      "      "      OCT 90 VERSION QLXINS
*Revision 002   M. Lepine - mars 98 - extensions pour fstd98
*
*LANGAGE      FTN77 
*
*ARGUMENTS
* ENTRE     - NI,NJ,NK - DIMENSIONS DE LA GRILLE
* ENTRE     - GRID     - TYPE DE GRILLE 
* ENTRE     - IG1@AG4  - DESCRIPTEURS DE LA GRILLE
*
*OBJET(CRITSUP)
*              DEFIFIT DES DETAILS SUR LA GRILLE, ILS SERONT CONSIDERES
*              COMME CLES DE RECHERCHE APPLIQUABLES A TOUS LES DIRECTIVES
*              DESIRE & EXCLURE.
*
* NOTE:        LES DETAILS SERONT AUTOMATIQUEMENT DESACTIVES APRES EXECUTION
*              D'UNE DIRECTIVE SEQCOPI OU STDCOPI.
*
*MODULE
      EXTERNAL FSTCVT
*
*IMPLICITES
      INTEGER   NMR, NMS, NME, NMN, NMM, NMD
      PARAMETER(NMR=12, NMS=25, NME=20, NMN=40, NMM=10, NMD=20)
      COMMON/DESRS/  JOURS(4), NREQ, SAUV, DESEXC(NMD), SATISF(NMD),
     X               NEXC, REQ(11,4,NMD), SUP(8,NMD), NIS, NJS, NKS,
     X               IG1S, IG2S, IG3S, IG4S, REQN(NMD), REQT(NMD),
     X               REQE(NMD), Z1, Z2, Z3, ZD
      INTEGER        NREQ, SAUV, DESEXC, SATISF, NEXC, REQ, SUP, NIS, 
     X               NJS, NKS, IG1S, IG2S, IG3S, IG4S, REQN, REQT, REQE,
     X               JOURS, Z1, Z2, Z3, ZD
      COMMON/LOGIQ/  SCRI, XPRES, ESAIS, DM1, DEBUG, SELEC, BOX, DIAG,
     x               INTERAC, ZA
      LOGICAL        SCRI, XPRES, ESAIS, DM1, DEBUG, SELEC, BOX, DIAG,
     x               INTERAC, ZA
      COMMON /CHAR/  NS, ND, SNOM, DNOM, ZE, ETI, ETIS(10,NMD), 
     X               ZT, TYP, TYPS(10,NMD), GTY, GTYS(NMD), GTYPS,
     X               ZN, NOM, NOMS(10,NMD), ETAT
      CHARACTER *1   GTY, GTYS, GTYPS
      CHARACTER *2   ZT, TYP, TYPS
      CHARACTER *4   ZN, NOM, NOMS
      CHARACTER *6   ETAT
      CHARACTER *12  ZE, ETI, ETIS
      CHARACTER *128 NS, ND
      CHARACTER *15  SNOM, DNOM
      COMMON/FICHES/ NP, FIXD, ECR, SSEQ, VS, OUVS, DSEQ, VD, OUVD
      INTEGER        NP
      LOGICAL            FIXD, ECR, SSEQ, VS, OUVS, DSEQ, VD, OUVD
**
      INTEGER  I, FSTCVT
      CHARACTER*2 TV
      CHARACTER*4 NV
      CHARACTER*12 LBL
*     DESACTIVAGE DES CRITERES EN FONCRION
      IG4S = -1
      IG3S = -1
      IG2S = -1
      IG3S = -1
      GTYPS= ' '
      NKS  = -1
      NJS  = -1
      NIS  = -1
*     ACTIVAGE DES CRITERES FOURNIS PAR LA DIRECTIVE
      GO TO (8, 7, 6, 5, 4, 3, 2, 1) NP 
    1 IG4S = IG4
    2 IG3S = IG3
    3 IG2S = IG2
    4 IG3S = IG1
    5 I = FSTCVT(' ',' ',' ', GRID, NV, TV, LBL, GTYPS, .TRUE.)
    6 NKS  = NK
    7 NJS  = NJ
    8 NIS  = NI
*     DESACTIVER LES CRITERES SUPLEMENTAIRES AVEC "CTITSUP(-1)"
      IF(NP.EQ.1 .AND. NI.EQ.-1) THEN
         SCRI = .FALSE.
         IF( DEBUG ) PRINT*,'CRITERES SUPLEMENTAIRES DESACTIVES'
      ELSE
         IF( DEBUG ) THEN
            IF( SCRI ) THEN
               PRINT*,'CRITERES SUPLEMENTAIRES DE SELECTION MODIFIES' 
            ELSE
               PRINT*,'CRITERES SUPLEMENTAIRES DE SELECTION ACTIVES'
            ENDIF
         ENDIF
         SCRI = .TRUE.
      ENDIF
      RETURN
      END 
