*** S/R SAUVDEZ CONTROLE LA PORTEE DES DIRECTIVES APRES COPIE
      SUBROUTINE SAUVDEZ
      IMPLICIT NONE 
*
*AUTEURS
*VERSION ORIGINALE -   Y. BOURASSA NOV 89
*REVISION      001 -   Y. BOURASSA AVR 92 ANULE LE ZAP SI SAUV=0
*
*LANGUAGE   - FTN77 
*
      INTEGER   NMR, NMS, NME, NMN, NMM, NMD
      PARAMETER(NMR=12, NMS=25, NME=20, NMN=40, NMM=10, NMD=20)
      COMMON/FICHES/ NP, FIXD, ECR, SSEQ, VS, OUVS, DSEQ, VD, OUVD
      INTEGER        NP
      LOGICAL            FIXD, ECR, SSEQ, VS, OUVS, DSEQ, VD, OUVD
      COMMON/DESRS/  JOURS(4), NREQ, SAUV, DESEXC(NMD), SATISF(NMD),
     X               NEXC, REQ(11,4,NMD), SUP(8,NMD), NIS, NJS, NKS,
     X               IG1S, IG2S, IG3S, IG4S, REQN(NMD), REQT(NMD),
     X               REQE(NMD), Z1, Z2, Z3, ZD
      INTEGER        NREQ, SAUV, DESEXC, SATISF, NEXC, REQ, SUP, NIS, 
     X               NJS, NKS, IG1S, IG2S, IG3S, IG4S, REQN, REQT, REQE,
     X               JOURS, Z1, Z2, Z3, ZD
      COMMON /CHAR/  NS, ND, SNOM, DNOM, ZE, ETI, ETIS(10,NMD), 
     X               ZT, TYP, TYPS(10,NMD), GTY, GTYS(NMD), GTYPS,
     X               ZN, NOM, NOMS(10,NMD), ETAT
      CHARACTER *1   GTY, GTYS, GTYPS
      CHARACTER *2   ZT, TYP, TYPS
      CHARACTER *4   ZN, NOM, NOMS
      CHARACTER *6   ETAT
      CHARACTER *12  ZE, ETI, ETIS
      CHARACTER *128 NS, ND
      CHARACTER *15  SNOM, DNOM
*
*MODULE
      EXTERNAL FSTCVT, ZAP
*
**
      INTEGER  FSTCVT, I, J, N
*     SI LES DIRECTIVES RESTENT VALIDES
      IF( SAUV .LE. 0) THEN
         NP = 1
         CALL ZAP( -1 )
         IF( SAUV .LT. 0) RETURN  
      ENDIF
*     EFFACE TOUTE TRACE DES DESIRE/EXCLURE/CRITSUP INUTILES
      NREQ = SAUV
      DO 10 N=SAUV*77+1, 11*4*NMD
         REQ(N,1,1) = 0
   10    CONTINUE
      DO 20 N=SAUV*9+1, 8*NMD 
         SUP(N,1) = 0
   20    CONTINUE
      DO 30 N=SAUV+1, NMD
         REQN(N) = 0
         REQE(N) = 0
         REQT(N) = 0
         DO 30 J=1,10
            I = FSTCVT(-1, -1, -1, -1, NOMS(J,N), TYPS(J,N), ETIS(J,N),
     X              GTYS(N), .TRUE.)
   30       CONTINUE
*     CONTE LES EXCLUSIONS QUI RESTENT EN FORCE
      NEXC = 0
      IF(SAUV .GT. 0) THEN
         DO 40 N=1,SAUV
            SATISF(N) = 0
            IF(DESEXC(N) .EQ. 0) NEXC = NEXC + 1
   40       CONTINUE
      ENDIF
      RETURN
      END 
